<?php

use App\Models\Section;
use App\Models\Study;
use Illuminate\Database\Seeder;
use App\Models\Cvteacherstudy;

class StudiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $types = [

//            ['id' => 1, 'name' => 'Διοίκηση Επιχειρήσεων', 'section_id' => 21], /**  IEK Επαγγελματικές Σπουδές 21-34 */
            //            ['id' => 1, 'name' => 'Στέλεχος Διοίκησης & Οικονομίας', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Διοίκηση Επιχειρήσεων', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Μηχανογραφημένου Λογιστηρίου - Φοροτεχνικού Γραφείου', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Μηχανογραφημένη Λογιστική', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Εμπορίας & Διαφήμισης & Προώθησης Προϊόντων (Marketing)', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Marketing', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Διοίκησης & Οικονομίας στον τομέα της Ναυτιλίας', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Ναυτιλιακά', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Σπουδές Ναυτιλιακών - Διοικητικά Στελέχη', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Γραμματέας Ανώτερων και Ανώτατων Στελεχών', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Γραμματέας Διεύθυνσης', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Ασφαλείας Προσώπων & Υποδομών', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Security', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Στατιστικών Ερευνών και Δημοσκοπήσεων', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Έρευνα Αγοράς & Δημοσκοπήσεις', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Υπηρεσιών Εφοδιαστικής Αλυσίδας', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Logistics', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Διοικητικό Στέλεχος Πολιτισμού', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Διοικητικό Στέλεχος Υγείας', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Διοικητικό Στέλεχος Μεταφορών', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Διοίκησης και Οικονομίας στον Τομέα των Μεταφορών', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Διαχείρισης Ακίνητης Περιουσίας (Real estate)', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Χρηματοοικονομικών και Ασφαλιστικών Εργασιών', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Τραπεζικά', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Διεθνούς Εμπορίου', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Ναυλομεσιτικών Εργασιών', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Τεχνολογίες Επικοινωνίας και Πληροφοριών στην Ταξιδιωτική Βιομηχανία (V.I.C.T. TRAVEL)', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Φύλακας Μουσείων & Αρχαιολογικών Χώρων', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Κοστολόγησης', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Τεχνικός Αγροτουρισμού', 'section_id' => 21],
            //            ['id' => 1, 'name' => 'Στέλεχος Διοίκησης και Οικονομίας στον Τομέα της Αγροτικής Οικονομίας', 'section_id' => 21],
            //
            //            ['id' => 1, 'name' => 'Βοηθός Φυσικοθεραπείας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Φυσικοθεραπεία', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Φαρμακείου - Τεχνικός Φαρμάκων/Καλλυντικών', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Τεχνικός Φαρμάκων', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Καλλυντικών και Παρεμφερών Προϊόντων', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Φαρμακείου', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Ακτινολόγου - Ραδιολόγου', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Ραδιολογίας & Ακτινολογίας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Μαιευτικής', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Μαιευτική', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Μαιευτικής', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Νοσηλευτική', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Στέλεχος Διατροφής & Διαιτολογίας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Διαιτητική', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Μικροβιολόγου', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Ιατρικών Εργαστηρίων', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Εργοθεραπείας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Εργοθεραπεία', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Γενικής Νοσηλείας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Τραυματολογίας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Χειρουργείου', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Ογκολογικών Παθήσεων', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Μονάδων Εντατικής Θεραπείας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Νοσηλευτικής Ατόμων με Ειδικές Παθήσεις', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Οδοντικής Τεχνολογίας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Βοηθός Οπτικής και Οπτικομετρίας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Τεχνικός Φαρμάκων Καλλυντικών & Παρεμφερών Προϊόντων', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Διασώστης - Πλήρωμα Ασθενοφόρου', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Σπουδές Επείγουσας Ιατρικής Φροντίδας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Ρεφλεξολογία', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Φροντίδα Τρίτης Ηλικίας', 'section_id' => 22],
            //            ['id' => 1, 'name' => 'Θεραπευτική Ιππασία και Ιπποθεραπεία', 'section_id' => 22],
            //
            //            ['id' => 1, 'name' => 'Σκηνοθεσία', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Τέχνη Σκηνοθεσίας', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Μοντάζ-Monter', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Χειριστής Συνάρμοσης Εικόνας (Monter)', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Εικονοληψία', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Σκηνογράφος-Ενδυματολόγος', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Σεναριογραφία', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Τέχνη Σεναριογραφίας', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Χορός', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Μουσική - Τραγούδι', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Εφαρμομένες Τέχνες Χορού', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Υποκριτική Τέχνη Θεάτρου-Κινηματογράφου', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Υποκριτική', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Μετάφραση, Διόρθωση & Επιμέλεια κειμένων', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Τέχνη Δημιουργικής Γραφής', 'section_id' => 23],
            //            ['id' => 1, 'name' => 'Οργανωτικός Συντονιστής Παραγωγής', 'section_id' => 23],
            //
            //            ['id' => 1, 'name' => 'Μηχανικός Αυτοκινήτων, Σκαφών Θαλάσσης & Μοτοσικλετών', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Μηχανοτρονικής', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Εσωτερικών Ηλεκτρικών Εγκαταστάσεων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Ανελκυστήρων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Μηχανικός Σκηνής - Φροντιστής', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Ηλεκτρολόγος', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Ηλεκτρολόγος Εσωτερικών Εγκαταστάσεων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Εγκαταστάσεων Ψύξης Αερισμού & Κλιματισμού', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Ψυκτικός', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Αυτοματισμών', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Μηχανικός Θερμικών Εγκαταστάσεων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Ραδιοτηλεοπτικών και Ηλεκτροακουστικών Διατάξεων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Μηχανικός Θερμικών Εγκαταστάσεων & Μηχανικός Τεχνολογίας Πετρελαίου και Φυσικού Αερίου', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Εκπαιδευτής Οδηγών', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Εκπαιδευτής Υποψηφίων Οδηγών Αυτοκινήτων & Μοτοσικλετών', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Ιατρικών Οργάνων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Εγκασταστάσεων Ανανεώσιμων Πηγών Ενέργειας', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Κυβερνήτης Σκαφών Αναψυχής', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Μηχανικός - Τεχνικός Μηχανών Θαλάσσης', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Θερμοϋδραυλικός', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Μηχανικός - Τεχνικός Αυτοκινήτων', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Τεχνικός Βιομηχανικού Εξοπλισμού', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Ηλεκτρονική', 'section_id' => 24],
            //            ['id' => 1, 'name' => 'Ηλιακή και Αιολική Ενέργεια', 'section_id' => 24],
            //
            //            ['id' => 1, 'name' => 'Τεχνικός Μαγειρικής Τέχνης - Αρχιμάγειρας (Chef)', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Σεφ', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Τεχνικός Αρτοποιός - Ζαχαροπλαστικής', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Αρτοποιία - Ζαχαροπλαστική', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Υπεύθυνος Μονάδας Συστηματοποιημένου Επισιτισμού (Catering)', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Ξενοδοχειακά', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Σπουδές Ξενοδοχειακών', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Τεχνικός Τουριστικών Mονάδων και Επιχειρήσεων Φιλοξενίας', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Υπάλληλος Τουριστικού Γραφείου', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Τουριστικοί Πράκτορες', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Στέλεχος Διοίκησης και Οικονομίας στον τομέα του Τουρισμού', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Υπεύθυνος Υποδοχής - Ρεσεψιονίστ Ξενοδοχείου', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Διευθυντής (Manager) Ξενοδοχείου', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Σπουδές Θρησκευτικού Τουρισμού και Προσκυνηματικών Περιηγήσεων', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Τουριστικός Συνοδός', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Συνοδός Βουνού', 'section_id' => 25],
            //            ['id' => 1, 'name' => 'Στέλεχος Κρουαζιερόπλοιων', 'section_id' => 25],
            //
            //            ['id' => 1, 'name' => 'Σχεδιαστής Μόδας-Τεχνικός Τεχνολογίας Ενδύματος & Υποδήματος', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Σχεδιαστής Μόδας - Stylists', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Fashion Designer', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Make Up Artist', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Τεχνικός Κομμωτικής Τέχνης', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Κομμωτική', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Τεχνικός Κομμωτικής Τέχνης', 'section_id' => 26],
            //            ['id' => 1, 'name' => 'Τεχνικός Αισθητικής Τέχνης & Μακιγιάζ', 'section_id' => 26],
            //
            //            ['id' => 1, 'name' => 'Αισθητική', 'section_id' => 27],
            //            ['id' => 1, 'name' => 'Τεχνικός Αισθητικής Τέχνης & Μακιγιάζ', 'section_id' => 27],
            //            ['id' => 1, 'name' => 'Αισθητικός Ποδολογίας & Καλλωπισμού Νυχιών', 'section_id' => 27],
            //            ['id' => 1, 'name' => 'Τεχνικός Αισθητικός Ποδολογίας Καλλωπισμού Νυχιών & Ονυχοπλαστικής', 'section_id' => 27],
            //            ['id' => 1, 'name' => 'Θαλασσοθεραπεία - Spa', 'section_id' => 27],
            //            ['id' => 1, 'name' => 'Στέλεχος Θαλασσοθεραπείας - Λουτροθεραπείας - Spa', 'section_id' => 27],
            //
            //            ['id' => 1, 'name' => 'Βοηθός Βρεφονηπιοκόμου', 'section_id' => 28],
            //            ['id' => 1, 'name' => 'Σπουδές Προσχολικής Αγωγής', 'section_id' => 28],
            //            ['id' => 1, 'name' => 'Φροντιστής παιδιών προσχολικής ηλικίας - Baby Sitting', 'section_id' => 28],
            //            ['id' => 1, 'name' => 'Σπουδές Προσχολικής Αγωγής Δραστηριοτήτων Δημιουργίας και Έκφρασης', 'section_id' => 28],
            //
            //            ['id' => 1, 'name' => 'Ηχοληψία', 'section_id' => 29],
            //            ['id' => 1, 'name' => 'Μουσική Τεχνολογία', 'section_id' => 29],
            //            ['id' => 1, 'name' => 'Ραδιοφωνικός Παραγωγός', 'section_id' => 29],
            //            ['id' => 1, 'name' => 'Τηλεοπτικός Παραγωγός', 'section_id' => 29],
            //
            //            ['id' => 1, 'name' => 'Τεχνικός Εφαρμογών Πληροφορικής (Πολυμέσα/Web Designer-Developer/ Vsection_ideo games)', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Web Designer - Web Developer', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Web Design - Vsection_ideo Games', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Tεχνικός Δικτύων & Τηλεπικοινωνιών', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Τεχνικός Δικτύων και Αυτοματισμού Γραφείου', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Τεχνικός Η/Υ', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Τεχνικός Λογισμικού Η/Υ', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Προγραμματιστής', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Τεχνικός Ιατρικής Πληροφορικής', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'CISCO CCNA Certified Security', 'section_id' => 30],
            //            ['id' => 1, 'name' => 'Προγραμματιστής Εφαρμογών Android', 'section_id' => 30],
            //
            //            ['id' => 1, 'name' => 'Γραφίστας', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Γραφιστική Εντύπου & Ηλεκτρονικών Μέσων', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Εικονογράφος - Σκιτσογράφος', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Τέχνη Σκίτσου - Εικονογραφίας - Γραφικών', 'section_id' => 31],
            //            ['id' => 1, 'name' => '3D Αnimation', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Τεχνικός Κινούμενης Εικόνας - Ηλεκτρονικής Σχεδίασης Γραφήματος', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Διακοσμητής', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Εσωτερική Αρχιτεκτονική Διακόσμηση & Σχεδιασμός Αντικειμένων', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Φωτογράφος', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Σχεδιαστής μέσω Συστημάτων Η/Υ - CAD', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Ζωγραφική Τέχνη', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Σχεδιαστής Δομικών Έργων και Γεωπληροφορικής', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Δομικός', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Σπουδές Δομικών Έργων', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Τεχνικός Τεχνολογικών Εφαρμογών & Εγκαταστάσεων', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Συντηρητής Έργων Τέχνης και Αρχαιοτήτων', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Τεχνικός Συντήρησης Έργων Ζωγραφικής', 'section_id' => 31],
            //            ['id' => 1, 'name' => 'Τέχνη Τοιχογραφίας', 'section_id' => 31],
            //
            //            ['id' => 1, 'name' => 'Δημοσιογραφία, Συντακτών & Ρεπόρτερ', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Δημοσιογράφος', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Αθλητικός Δημοσιογράφος', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Αθλητική Δημοσιογραφία', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Προπονητής Αθλημάτων', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Sports Management', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Παραγωγή', 'section_id' => 32],
            //            ['id' => 1, 'name' => 'Διοικητικό Στέλεχος Αθλητισμού', 'section_id' => 32],
            //
            //            ['id' => 1, 'name' => 'Διαχειριστής Γεωργοκτηνοτροφικών Εκμεταλλεύσεων', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Farm Management', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Αμπελουργίας & Οινολογίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Γαλακτοκομίας – Τυροκόμος', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Δασικής Προστασίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Θερμοκηπίων και Καλλιεργιών υπό Κάλυψη', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Μελισσοκομίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Οικολογικής & Βιολογικής Γεωργίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Βιολογικής - Οργανικής Γεωργίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Συντήρησης και Επισκευής Γεωργικών Μηχανημάτων', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Διοίκηση Αγροτικής Οικονομίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Αγροτουρισμός', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Ανθοκομία', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Αρδεύσεις', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Δενδροκομία & Μεταποίηση Προϊόντων Ελιάς', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Δενδροκομίας και Εναλλακτικών Δενδρωδών Καλλιεργιών', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Τεχνικός Ποτοποιίας - Αποσταγματοποιίας', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Στέλεχος Επιχειρήσεων Τυποποίησης, Μεταποίησης και Εμπορίας Αγροτικών Προϊόντων', 'section_id' => 33],
            //            ['id' => 1, 'name' => 'Διαχειριστής Συστημάτων Εκτροφής Αγροτικών Ζώων', 'section_id' => 33],
            //
            //            ['id' => 1, 'name' => 'Κομμωτική Σκύλων', 'section_id' => 34],
            //            ['id' => 1, 'name' => 'Βοηθός Κτηνιατρικής Κλινικής', 'section_id' => 34],
            //
            //            ['id' => 1, 'name' => 'BA (Hons) Business Management (Διοίκηση Επιχειρήσεων)', 'section_id' => 1], /**  κολλεγια Bachelor 1-10 */
            //            ['id' => 1, 'name' => 'BA (Hons) Marketing (Μάρκετινγκ)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) Economics for Business (Οικονομικά)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) Economics (Οικονομικά)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Business Administration, Concentration in Finance', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Business Administration, Concentration in International Business', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Business Administration, Concentration in Entrepreneurial Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Business Administration, Concentration in Marketing', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Business Administration, Concentration in Hospitality and Tourism', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA (Hons) Business Studies', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA in International Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA in Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc Concentration in Business Communications', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc Concentration in Finance', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc Concentration in International Business', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc Concentration in Marketing', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Accounting', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Applied Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc in Business Administration', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA (Hons) - Business Studies (Finance and Accounting)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA (Hons) - Business Studies (Management)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA (Hons) - Business Studies (Marketing)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA (Hons) - Business Studies (Hotel and Hospitality)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (Entrepreneurship Management)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (Accounting with Finance)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (International Business)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (Marketing Communications)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (Marketing Management)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (Human Resource Management)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Business Administration (Operations Management)', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Finance', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Healthcare Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in International Tourism and Hospitality Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Logistics and Supply Chain Management', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Management Information Systems', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA (Hons) in Business with Shipping', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA Διοίκηση Επιχειρήσεων', 'section_id' => 1],
            //            ['id' => 1, 'name' => 'BA Διοίκηση Ξενοδοχειακών Μονάδων και Επιχειρήσεων Φιλοξενίας', 'section_id' => 1],
            //
            //            ['id' => 1, 'name' => 'BSc (Hons) Maritime Business (Ναυτιλιακές Σπουδές)', 'section_id' => 2],
            //            ['id' => 1, 'name' => 'BSc (Hons) Shipping and Port Management(Διοίκηση Λιμένων και Ναυτιλιακών Επιχειρήσεων)', 'section_id' => 2],
            //            ['id' => 1, 'name' => 'BA in Marine Electrical Engineering', 'section_id' => 2],
            //            ['id' => 1, 'name' => 'BA in Navigation', 'section_id' => 2],
            //
            //            ['id' => 1, 'name' => 'BA (Hons) International Hospitality and Tourism Management(Τουρισμός και Ξενοδοχειακές Επιχειρήσεις', 'section_id' => 3],
            //            ['id' => 1, 'name' => 'BA Culinary Arts and Food Service Development (Επισιτιστικές Τέχνες και Ανάπτυξη Υπηρεσιών Εστίασης', 'section_id' => 3],
            //            ['id' => 1, 'name' => 'BA Culinary Arts, Baking and Patisserie  (Αρτοποιία / Ζαχαροπλαστική', 'section_id' => 3],
            //            ['id' => 1, 'name' => 'BA (Hons) in Business Studies with Tourism', 'section_id' => 3],
            //            ['id' => 1, 'name' => 'BSc (Hons) International Hospitality Management', 'section_id' => 3],
            //
            //            ['id' => 1, 'name' => 'BSc (Hons) Computing (Πληροφορική)', 'section_id' => 4],
            //            ['id' => 1, 'name' => 'BSc (Hons) Computer Networks (Πληροφορική και Δίκτυα Η/Υ)', 'section_id' => 4],
            //            ['id' => 1, 'name' => 'BEng (Hons) Electrical & Electronic Systems (Ηλεκτρολόγων – Ηλεκτρονικών Μηχανικών)', 'section_id' => 4],
            //            ['id' => 1, 'name' => 'BSc of Science in Computer Science', 'section_id' => 4],
            //            ['id' => 1, 'name' => 'BSc of Science in Business and Computing', 'section_id' => 4],
            //            ['id' => 1, 'name' => 'BSc Πληροφορική', 'section_id' => 4],
            //
            //            ['id' => 1, 'name' => 'BSc (Hons) Nursing (Νοσηλευτική)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Logopeadics (Λογοθεραπεία)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Physiotherapy (Φυσικοθεραπεία)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Biomedical Sciences (Βιοϊατρικές Επιστήμες)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Sports Coaching (Προπονητική)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Biomedical Sciences (Βιοϊατρικές Επιστήμες)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Sports Coaching (Προπονητική)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Dietetics (Διαιτολογία)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Occupational Therapy (Εργοθεραπεία)', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Biomedical Sciences', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Human Nutrition', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Psychology', 'section_id' => 5],
            //            ['id' => 1, 'name' => 'BSc (Hons) Extended in Science', 'section_id' => 5],
            //
            //            ['id' => 1, 'name' => 'BSc (Hons) Psychology (Ψυχολογία)', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA (Hons) Early Childhood Studies (Προσχολική Ηλικία)', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA (Hons) Special Education (Ειδική Αγωγή)', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA of Laws (LLB) (Νομική)', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BSc (Hons) Politics and International Relations (Πολιτικές Επιστήμες και Διεθνείς Σχέσεις)', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA (Hons) in English Language and English Language Teaching', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA (Hons) in Film Studies', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA Concentration Communication: Mass Media Production', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA Concentration in International Relations', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BSc Concentration in Psychology', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA (Hons) International Studies', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BSc of Arts in International Relations', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BSc of Arts in English', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BSc Ψυχολογία', 'section_id' => 6],
            //            ['id' => 1, 'name' => 'BA Αγγλική Γλώσσα και Γλωσσολογία', 'section_id' => 6],
            //
            //            ['id' => 1, 'name' => 'BA (Hons) Architecture (Αρχιτεκτονική)', 'section_id' => 7],
            //            ['id' => 1, 'name' => 'BEng (Hons) Civil Engineering & Construction (Πολιτικών Μηχανικών)', 'section_id' => 7],
            //            ['id' => 1, 'name' => 'BEng (Hons) Electrical and Electronic Systems (Ηλεκτρολόγων - Ηλεκτρονικών Μηχανικών)', 'section_id' => 7],
            //            ['id' => 1, 'name' => 'BEng (Hons) / MEng Mechanical Engineering and Manufacturing  (Μηχανολόγων Μηχανικών)', 'section_id' => 7],
            //
            //            ['id' => 1, 'name' => 'BA in Media Production - Journalism (Δημοσιογραφία)', 'section_id' => 8],
            //            ['id' => 1, 'name' => 'BA in Media Production - Film Directing (Σκηνοθεσία Κινηματογράφου)', 'section_id' => 8],
            //            ['id' => 1, 'name' => 'BSc (Hons) Music Technology (Μουσική Τεχνολογία)', 'section_id' => 8],
            //
            //            ['id' => 1, 'name' => 'BA (Hons) in Communication', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BA (Hons) in Economics', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BA (Hons) in English (English and American Literature)', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BA (Hons) in English (English Literature with Linguistics)', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Environmental Studies', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BA (Hons) in History', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BA (Hons) in Philosophy', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BA (Hons) in Sociology', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Information Technology (Software Development)', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Information Technology (Digital Media Technologies)', 'section_id' => 9],
            //            ['id' => 1, 'name' => 'BSc (Hons) in Information Technology (Network Technologies)', 'section_id' => 9],
            //
            //            ['id' => 1, 'name' => 'BA (Hons) in Art History', 'section_id' => 10],
            //            ['id' => 1, 'name' => 'BA (Hons) in Contemporary Dance Practice', 'section_id' => 10],
            //            ['id' => 1, 'name' => 'BA (Hons) in Graphic Design', 'section_id' => 10],
            //            ['id' => 1, 'name' => 'BA (Hons) in Music and Music Performance', 'section_id' => 10],
            //            ['id' => 1, 'name' => 'BA (Hons) in Theater Arts', 'section_id' => 10],
            //            ['id' => 1, 'name' => 'BA (Hons) in Visual Arts', 'section_id' => 10],
            //
            //            ['id' => 1, 'name' => 'MBA International Business (Μεταπτυχιακό στη Διοίκηση Επιχειρήσεων)', 'section_id' => 11], /**  κολλεγια Master 11-20 **/
            //            ['id' => 1, 'name' => 'MBA (Διοίκηση Επιχειρήσεων)', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Banking and Finance', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Finance', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Entrepreneurship', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in General Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Marketing', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Marketing in the Digital Era', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA Executive', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Logistics Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Healthcare Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MBA in Human Resource Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MA in International Management – Accounting & Finance', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MA in International Management – Aviation Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MA in International Management – International Marketing', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MA in Transport and Logistics Management', 'section_id' => 11],
            //            ['id' => 1, 'name' => 'MSc Global Shipping Management', 'section_id' => 11],
            //
            //            ['id' => 1, 'name' => 'MSc in Marine Engineering Management', 'section_id' => 12],
            //
            //            ['id' => 1, 'name' => 'MBA in Hospitality (Μεταπτυχιακό στη Διοίκηση Ξενοδοχειακών Επιχειρήσεων)', 'section_id' => 13],
            //            ['id' => 1, 'name' => 'MS in Hospitality and Tourism Management', 'section_id' => 13],
            //            ['id' => 1, 'name' => 'Master 2 Management - Management of International Tourism', 'section_id' => 13],
            //
            //            ['id' => 1, 'name' => 'MSc Software Engineering (Μεταπτυχιακό στη Μηχανική Λογισμικού)', 'section_id' => 14],
            //            ['id' => 1, 'name' => 'MSc Information Technology (Μεταπτυχιακό στην Τεχνολογία Πληροφοριών)', 'section_id' => 14],
            //            ['id' => 1, 'name' => 'MSc Information Security and Computer Forensics (Μεταπτυχιακό στην Ασφάλεια Πληροφοριών και την Ηλεκτρονική Εγκληματολογία)', 'section_id' => 14],
            //            ['id' => 1, 'name' => 'MSc in Internet Engineering and Web Management', 'section_id' => 14],
            //
            //            ['id' => 1, 'name' => 'MSc Physiotherapy (Μεταπτυχιακό στη Φυσικοθεραπεία)', 'section_id' => 15],
            //            ['id' => 1, 'name' => 'MSc Advanced Dietetic Practice (Μεταπτυχιακό Πρόγραμμα στην Προηγμένη Διαιτολογική Πρακτική)', 'section_id' => 15],
            //            ['id' => 1, 'name' => 'MPhil - Psychology Specialisms', 'section_id' => 15],
            //            ['id' => 1, 'name' => 'MSc in Cognitive Behavioural Psychotherapies', 'section_id' => 15],
            //            ['id' => 1, 'name' => 'MSc in Psychology', 'section_id' => 15],
            //
            //            ['id' => 1, 'name' => 'MA Special Educational Needs (SEN) (Μεταπτυχιακό στην Ειδική Αγωγή)', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'ΜSc Clinical & Community Psychology (Μεταπτυχιακό στην Κλινική Κοινοτική Ψυχολογία)', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MSc Business Psychology (Μεταπτυχιακό στην Ψυχολογία της Εργασίας)', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MSc Psychology (Μεταπτυχιακό στην Ψυχολογία)', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MS in Counseling Psychology & Psychotherapy', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MA in Applied Educational Psychology', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MA in Strategic Communication & Public Relations', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MA in Digital Communication & Social Media', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MA in Teaching English to Speakers of Other Languages', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MA Counselling and Psychotherapy (Μεταπτυχιακό στη Συμβουλευτική και τη Ψυχοθεραπεία)', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MSc Applied Positive Psychology and Coaching (Εφαρμοσμένη Θετική Ψυχολογία και Ψυχολογία Coaching)', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MA Second Language Learning and Teaching', 'section_id' => 16],
            //            ['id' => 1, 'name' => 'MPhil - Education Specialisms', 'section_id' => 16],
            //
            //            ['id' => 1, 'name' => 'MArch Architecture and Urbanism (Μεταπτυχιακό στην Αρχιτεκτονική και τον Αστικό Σχεδιασμό)', 'section_id' => 17],
            //            ['id' => 1, 'name' => 'MSc Civil Engineering and the Built Environment (Μεταπτυχιακό Πολιτικών Μηχανικών)', 'section_id' => 17],
            //            ['id' => 1, 'name' => 'MSc Electronic Systems Engineering (Μεταπτυχιακό Ηλεκτρονικών Μηχανικών)', 'section_id' => 17],
            //            ['id' => 1, 'name' => 'MSc Electrical Engineering and Computer Systems', 'section_id' => 17],
            //            ['id' => 1, 'name' => 'MSc in Civil Engineering', 'section_id' => 17],
            //
            //            ['id' => 1, 'name' => 'Ανθρωπιστικές Επιστήμες', 'section_id' => 35], /**  Φροντιστήρια Μέσης Εκπαίδευσης   */
            //            ['id' => 1, 'name' => 'Θετικές & Τεχνολογικές Επιστήμες', 'section_id' => 35],
            //            ['id' => 1, 'name' => 'Επιστήμες Υγείας', 'section_id' => 35],
            //            ['id' => 1, 'name' => 'Επιστήμες Οικονομίας και Πληροφορικής', 'section_id' => 35],
            //            ['id' => 1, 'name' => 'Επιστήμες Εκπαίδευσης', 'section_id' => 35],
            //
            //            ['id' => 1, 'name' => 'Θετικές & Τεχνολογικές Επιστήμες', 'section_id' => 36],
            //            ['id' => 1, 'name' => 'Ανθρωπιστικές Επιστήμες', 'section_id' => 36],
            //
            //            ['id' => 1, 'name' => 'Αγγλικά', 'section_id' => 38], /**  Φροντιστήρια Ξένων Γλωσσών Πληροφορικής  */
            //            ['id' => 1, 'name' => 'Γαλλικά', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Γερμανικά', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Ιταλικά', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Ισπανικά', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Ρωσικά', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Κινέζικα', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Βουλγάρικα', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Τουρκικά', 'section_id' => 38],
            //            ['id' => 1, 'name' => 'Πληροφορική', 'section_id' => 41],
            //            ['id' => 1, 'name' => 'Ρομποτική', 'section_id' => 41],
            //
            //            ['id' => 1, 'name' => 'Αγγλικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Γαλλικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Γερμανικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Ιταλικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Ισπανικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Ρωσικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Κινέζικα', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Βουλγάρικα', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Τουρκικά', 'section_id' => 39],
            //            ['id' => 1, 'name' => 'Πληροφορική', 'section_id' => 42],
            //            ['id' => 1, 'name' => 'Ρομποτική', 'section_id' => 42],
            //
            //            ['id' => 1, 'name' => 'Αγγλικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Γαλλικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Γερμανικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Ιταλικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Ισπανικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Ρωσικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Κινέζικα', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Βουλγάρικα', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Τουρκικά', 'section_id' => 40],
            //            ['id' => 1, 'name' => 'Πληροφορική', 'section_id' => 43],
            //            ['id' => 1, 'name' => 'Ρομποτική', 'section_id' => 43],
            //
            //            ['id' => 1, 'name' => 'Latin', 'section_id' => 44], /**  Σχολές Χορού */
            //            ['id' => 1, 'name' => 'Tango', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Oriental', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Ελληνικοί Χοροί', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Κλασσικός Χορός', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Σύγχρονος Χορός', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Zumba-Fitness', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Ballroom', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Hip Hop', 'section_id' => 44],
            //            ['id' => 1, 'name' => 'Salsa', 'section_id' => 44],
            //
            //            ['id' => 1, 'name' => 'Latin', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Tango', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Oriental', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Ελληνικοί Χοροί', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Κλασσικός Χορός', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Σύγχρονος Χορός', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Zumba-Fitness', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Ballroom', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Hip Hop', 'section_id' => 45],
            //            ['id' => 1, 'name' => 'Salsa', 'section_id' => 45],
            //
            //            ['id' => 1, 'name' => 'Latin', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Tango', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Oriental', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Ελληνικοί Χοροί', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Κλασσικός Χορός', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Σύγχρονος Χορός', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Zumba-Fitness', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Ballroom', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Hip Hop', 'section_id' => 46],
            //            ['id' => 1, 'name' => 'Salsa', 'section_id' => 46],

            ['name' => 'Διοίκηση Επιχειρήσεων', 'id' => 21], /**  IEK Επαγγελματικές Σπουδές 21-34 */
            ['name' => 'Στέλεχος Διοίκησης & Οικονομίας', 'id' => 21],
            ['name' => 'Στέλεχος Μηχανογραφημένου Λογιστηρίου - Φοροτεχνικού Γραφείου', 'id' => 21],
            ['name' => 'Μηχανογραφημένη Λογιστική', 'id' => 21],
            ['name' => 'Στέλεχος Εμπορίας & Διαφήμισης & Προώθησης Προϊόντων (Marketing)', 'id' => 21],
            ['name' => 'Marketing', 'id' => 21],
            ['name' => 'Στέλεχος Διοίκησης & Οικονομίας στον τομέα της Ναυτιλίας', 'id' => 21],
            ['name' => 'Ναυτιλιακά', 'id' => 21],
            ['name' => 'Σπουδές Ναυτιλιακών - Διοικητικά Στελέχη', 'id' => 21],
            ['name' => 'Γραμματέας Ανώτερων και Ανώτατων Στελεχών', 'id' => 21],
            ['name' => 'Γραμματέας Διεύθυνσης', 'id' => 21],
            ['name' => 'Στέλεχος Ασφαλείας Προσώπων & Υποδομών', 'id' => 21],
            ['name' => 'Security', 'id' => 21],
            ['name' => 'Στέλεχος Στατιστικών Ερευνών και Δημοσκοπήσεων', 'id' => 21],
            ['name' => 'Έρευνα Αγοράς & Δημοσκοπήσεις', 'id' => 21],
            ['name' => 'Στέλεχος Υπηρεσιών Εφοδιαστικής Αλυσίδας', 'id' => 21],
            ['name' => 'Logistics', 'id' => 21],
            ['name' => 'Διοικητικό Στέλεχος Πολιτισμού', 'id' => 21],
            ['name' => 'Διοικητικό Στέλεχος Υγείας', 'id' => 21],
            ['name' => 'Διοικητικό Στέλεχος Μεταφορών', 'id' => 21],
            ['name' => 'Στέλεχος Διοίκησης και Οικονομίας στον Τομέα των Μεταφορών', 'id' => 21],
            ['name' => 'Στέλεχος Διαχείρισης Ακίνητης Περιουσίας (Real estate)', 'id' => 21],
            ['name' => 'Στέλεχος Χρηματοοικονομικών και Ασφαλιστικών Εργασιών', 'id' => 21],
            ['name' => 'Τραπεζικά', 'id' => 21],
            ['name' => 'Στέλεχος Διεθνούς Εμπορίου', 'id' => 21],
            ['name' => 'Στέλεχος Ναυλομεσιτικών Εργασιών', 'id' => 21],
            ['name' => 'Τεχνολογίες Επικοινωνίας και Πληροφοριών στην Ταξιδιωτική Βιομηχανία (V.I.C.T. TRAVEL)', 'id' => 21],
            ['name' => 'Φύλακας Μουσείων & Αρχαιολογικών Χώρων', 'id' => 21],
            ['name' => 'Στέλεχος Κοστολόγησης', 'id' => 21],
            ['name' => 'Τεχνικός Αγροτουρισμού', 'id' => 21],
            ['name' => 'Στέλεχος Διοίκησης και Οικονομίας στον Τομέα της Αγροτικής Οικονομίας', 'id' => 21],

            ['name' => 'Βοηθός Φυσικοθεραπείας', 'id' => 22],
            ['name' => 'Φυσικοθεραπεία', 'id' => 22],
            ['name' => 'Βοηθός Φαρμακείου - Τεχνικός Φαρμάκων/Καλλυντικών', 'id' => 22],
            ['name' => 'Τεχνικός Φαρμάκων', 'id' => 22],
            ['name' => 'Καλλυντικών και Παρεμφερών Προϊόντων', 'id' => 22],
            ['name' => 'Βοηθός Φαρμακείου', 'id' => 22],
            ['name' => 'Βοηθός Ακτινολόγου - Ραδιολόγου', 'id' => 22],
            ['name' => 'Βοηθός Ραδιολογίας & Ακτινολογίας', 'id' => 22],
            ['name' => 'Βοηθός Μαιευτικής', 'id' => 22],
            ['name' => 'Μαιευτική', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Μαιευτικής', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής', 'id' => 22],
            ['name' => 'Νοσηλευτική', 'id' => 22],
            ['name' => 'Στέλεχος Διατροφής & Διαιτολογίας', 'id' => 22],
            ['name' => 'Διαιτητική', 'id' => 22],
            ['name' => 'Βοηθός Μικροβιολόγου', 'id' => 22],
            ['name' => 'Βοηθός Ιατρικών Εργαστηρίων', 'id' => 22],
            ['name' => 'Βοηθός Εργοθεραπείας', 'id' => 22],
            ['name' => 'Εργοθεραπεία', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Γενικής Νοσηλείας', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Τραυματολογίας', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Χειρουργείου', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Ογκολογικών Παθήσεων', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Μονάδων Εντατικής Θεραπείας', 'id' => 22],
            ['name' => 'Βοηθός Νοσηλευτικής Ατόμων με Ειδικές Παθήσεις', 'id' => 22],
            ['name' => 'Βοηθός Οδοντικής Τεχνολογίας', 'id' => 22],
            ['name' => 'Βοηθός Οπτικής και Οπτικομετρίας', 'id' => 22],
            ['name' => 'Τεχνικός Φαρμάκων Καλλυντικών & Παρεμφερών Προϊόντων', 'id' => 22],
            ['name' => 'Διασώστης - Πλήρωμα Ασθενοφόρου', 'id' => 22],
            ['name' => 'Σπουδές Επείγουσας Ιατρικής Φροντίδας', 'id' => 22],
            ['name' => 'Ρεφλεξολογία', 'id' => 22],
            ['name' => 'Φροντίδα Τρίτης Ηλικίας', 'id' => 22],
            ['name' => 'Θεραπευτική Ιππασία και Ιπποθεραπεία', 'id' => 22],

            ['name' => 'Σκηνοθεσία', 'id' => 23],
            ['name' => 'Τέχνη Σκηνοθεσίας', 'id' => 23],
            ['name' => 'Μοντάζ-Monter', 'id' => 23],
            ['name' => 'Χειριστής Συνάρμοσης Εικόνας (Monter)', 'id' => 23],
            ['name' => 'Εικονοληψία', 'id' => 23],
            ['name' => 'Σκηνογράφος-Ενδυματολόγος', 'id' => 23],
            ['name' => 'Σεναριογραφία', 'id' => 23],
            ['name' => 'Τέχνη Σεναριογραφίας', 'id' => 23],
            ['name' => 'Χορός', 'id' => 23],
            ['name' => 'Μουσική - Τραγούδι', 'id' => 23],
            ['name' => 'Εφαρμομένες Τέχνες Χορού', 'id' => 23],
            ['name' => 'Υποκριτική Τέχνη Θεάτρου-Κινηματογράφου', 'id' => 23],
            ['name' => 'Υποκριτική', 'id' => 23],
            ['name' => 'Μετάφραση, Διόρθωση & Επιμέλεια κειμένων', 'id' => 23],
            ['name' => 'Τέχνη Δημιουργικής Γραφής', 'id' => 23],
            ['name' => 'Οργανωτικός Συντονιστής Παραγωγής', 'id' => 23],

            ['name' => 'Μηχανικός Αυτοκινήτων, Σκαφών Θαλάσσης & Μοτοσικλετών', 'id' => 24],
            ['name' => 'Τεχνικός Μηχανοτρονικής', 'id' => 24],
            ['name' => 'Τεχνικός Εσωτερικών Ηλεκτρικών Εγκαταστάσεων', 'id' => 24],
            ['name' => 'Τεχνικός Ανελκυστήρων', 'id' => 24],
            ['name' => 'Μηχανικός Σκηνής - Φροντιστής', 'id' => 24],
            ['name' => 'Ηλεκτρολόγος', 'id' => 24],
            ['name' => 'Ηλεκτρολόγος Εσωτερικών Εγκαταστάσεων', 'id' => 24],
            ['name' => 'Τεχνικός Εγκαταστάσεων Ψύξης Αερισμού & Κλιματισμού', 'id' => 24],
            ['name' => 'Ψυκτικός', 'id' => 24],
            ['name' => 'Τεχνικός Αυτοματισμών', 'id' => 24],
            ['name' => 'Τεχνικός Μηχανικός Θερμικών Εγκαταστάσεων', 'id' => 24],
            ['name' => 'Τεχνικός Ραδιοτηλεοπτικών και Ηλεκτροακουστικών Διατάξεων', 'id' => 24],
            ['name' => 'Τεχνικός Μηχανικός Θερμικών Εγκαταστάσεων & Μηχανικός Τεχνολογίας Πετρελαίου και Φυσικού Αερίου', 'id' => 24],
            ['name' => 'Εκπαιδευτής Οδηγών', 'id' => 24],
            ['name' => 'Εκπαιδευτής Υποψηφίων Οδηγών Αυτοκινήτων & Μοτοσικλετών', 'id' => 24],
            ['name' => 'Τεχνικός Ιατρικών Οργάνων', 'id' => 24],
            ['name' => 'Τεχνικός Εγκασταστάσεων Ανανεώσιμων Πηγών Ενέργειας', 'id' => 24],
            ['name' => 'Κυβερνήτης Σκαφών Αναψυχής', 'id' => 24],
            ['name' => 'Μηχανικός - Τεχνικός Μηχανών Θαλάσσης', 'id' => 24],
            ['name' => 'Θερμοϋδραυλικός', 'id' => 24],
            ['name' => 'Μηχανικός - Τεχνικός Αυτοκινήτων', 'id' => 24],
            ['name' => 'Τεχνικός Βιομηχανικού Εξοπλισμού', 'id' => 24],
            ['name' => 'Ηλεκτρονική', 'id' => 24],
            ['name' => 'Ηλιακή και Αιολική Ενέργεια', 'id' => 24],

            ['name' => 'Τεχνικός Μαγειρικής Τέχνης - Αρχιμάγειρας (Chef)', 'id' => 25],
            ['name' => 'Σεφ', 'id' => 25],
            ['name' => 'Τεχνικός Αρτοποιός - Ζαχαροπλαστικής', 'id' => 25],
            ['name' => 'Αρτοποιία - Ζαχαροπλαστική', 'id' => 25],
            ['name' => 'Υπεύθυνος Μονάδας Συστηματοποιημένου Επισιτισμού (Catering)', 'id' => 25],
            ['name' => 'Ξενοδοχειακά', 'id' => 25],
            ['name' => 'Σπουδές Ξενοδοχειακών', 'id' => 25],
            ['name' => 'Τεχνικός Τουριστικών Mονάδων και Επιχειρήσεων Φιλοξενίας', 'id' => 25],
            ['name' => 'Υπάλληλος Τουριστικού Γραφείου', 'id' => 25],
            ['name' => 'Τουριστικοί Πράκτορες', 'id' => 25],
            ['name' => 'Στέλεχος Διοίκησης και Οικονομίας στον τομέα του Τουρισμού', 'id' => 25],
            ['name' => 'Υπεύθυνος Υποδοχής - Ρεσεψιονίστ Ξενοδοχείου', 'id' => 25],
            ['name' => 'Διευθυντής (Manager) Ξενοδοχείου', 'id' => 25],
            ['name' => 'Σπουδές Θρησκευτικού Τουρισμού και Προσκυνηματικών Περιηγήσεων', 'id' => 25],
            ['name' => 'Τουριστικός Συνοδός', 'id' => 25],
            ['name' => 'Συνοδός Βουνού', 'id' => 25],
            ['name' => 'Στέλεχος Κρουαζιερόπλοιων', 'id' => 25],

            ['name' => 'Σχεδιαστής Μόδας-Τεχνικός Τεχνολογίας Ενδύματος & Υποδήματος', 'id' => 26],
            ['name' => 'Σχεδιαστής Μόδας - Stylists', 'id' => 26],
            ['name' => 'Fashion Designer', 'id' => 26],
            ['name' => 'Make Up Artist', 'id' => 26],
            ['name' => 'Τεχνικός Κομμωτικής Τέχνης', 'id' => 26],
            ['name' => 'Κομμωτική', 'id' => 26],
            ['name' => 'Τεχνικός Κομμωτικής Τέχνης', 'id' => 26],
            ['name' => 'Τεχνικός Αισθητικής Τέχνης & Μακιγιάζ', 'id' => 26],

            ['name' => 'Αισθητική', 'id' => 27],
            ['name' => 'Τεχνικός Αισθητικής Τέχνης & Μακιγιάζ', 'id' => 27],
            ['name' => 'Αισθητικός Ποδολογίας & Καλλωπισμού Νυχιών', 'id' => 27],
            ['name' => 'Τεχνικός Αισθητικός Ποδολογίας Καλλωπισμού Νυχιών & Ονυχοπλαστικής', 'id' => 27],
            ['name' => 'Θαλασσοθεραπεία - Spa', 'id' => 27],
            ['name' => 'Στέλεχος Θαλασσοθεραπείας - Λουτροθεραπείας - Spa', 'id' => 27],

            ['name' => 'Βοηθός Βρεφονηπιοκόμου', 'id' => 28],
            ['name' => 'Σπουδές Προσχολικής Αγωγής', 'id' => 28],
            ['name' => 'Φροντιστής παιδιών προσχολικής ηλικίας - Baby Sitting', 'id' => 28],
            ['name' => 'Σπουδές Προσχολικής Αγωγής Δραστηριοτήτων Δημιουργίας και Έκφρασης', 'id' => 28],

            ['name' => 'Ηχοληψία', 'id' => 29],
            ['name' => 'Μουσική Τεχνολογία', 'id' => 29],
            ['name' => 'Ραδιοφωνικός Παραγωγός', 'id' => 29],
            ['name' => 'Τηλεοπτικός Παραγωγός', 'id' => 29],

            ['name' => 'Τεχνικός Εφαρμογών Πληροφορικής (Πολυμέσα/Web Designer-Developer/ Video games)', 'id' => 30],
            ['name' => 'Web Designer - Web Developer', 'id' => 30],
            ['name' => 'Web Design - Video Games', 'id' => 30],
            ['name' => 'Tεχνικός Δικτύων & Τηλεπικοινωνιών', 'id' => 30],
            ['name' => 'Τεχνικός Δικτύων και Αυτοματισμού Γραφείου', 'id' => 30],
            ['name' => 'Τεχνικός Η/Υ', 'id' => 30],
            ['name' => 'Τεχνικός Λογισμικού Η/Υ', 'id' => 30],
            ['name' => 'Προγραμματιστής', 'id' => 30],
            ['name' => 'Τεχνικός Ιατρικής Πληροφορικής', 'id' => 30],
            ['name' => 'CISCO CCNA Certified Security', 'id' => 30],
            ['name' => 'Προγραμματιστής Εφαρμογών Android', 'id' => 30],

            ['name' => 'Γραφίστας', 'id' => 31],
            ['name' => 'Γραφιστική Εντύπου & Ηλεκτρονικών Μέσων', 'id' => 31],
            ['name' => 'Εικονογράφος - Σκιτσογράφος', 'id' => 31],
            ['name' => 'Τέχνη Σκίτσου - Εικονογραφίας - Γραφικών', 'id' => 31],
            ['name' => '3D Αnimation', 'id' => 31],
            ['name' => 'Τεχνικός Κινούμενης Εικόνας - Ηλεκτρονικής Σχεδίασης Γραφήματος', 'id' => 31],
            ['name' => 'Διακοσμητής', 'id' => 31],
            ['name' => 'Εσωτερική Αρχιτεκτονική Διακόσμηση & Σχεδιασμός Αντικειμένων', 'id' => 31],
            ['name' => 'Φωτογράφος', 'id' => 31],
            ['name' => 'Σχεδιαστής μέσω Συστημάτων Η/Υ - CAD', 'id' => 31],
            ['name' => 'Ζωγραφική Τέχνη', 'id' => 31],
            ['name' => 'Σχεδιαστής Δομικών Έργων και Γεωπληροφορικής', 'id' => 31],
            ['name' => 'Δομικός', 'id' => 31],
            ['name' => 'Σπουδές Δομικών Έργων', 'id' => 31],
            ['name' => 'Τεχνικός Τεχνολογικών Εφαρμογών & Εγκαταστάσεων', 'id' => 31],
            ['name' => 'Συντηρητής Έργων Τέχνης και Αρχαιοτήτων', 'id' => 31],
            ['name' => 'Τεχνικός Συντήρησης Έργων Ζωγραφικής', 'id' => 31],
            ['name' => 'Τέχνη Τοιχογραφίας', 'id' => 31],

            ['name' => 'Δημοσιογραφία, Συντακτών & Ρεπόρτερ', 'id' => 32],
            ['name' => 'Δημοσιογράφος', 'id' => 32],
            ['name' => 'Αθλητικός Δημοσιογράφος', 'id' => 32],
            ['name' => 'Αθλητική Δημοσιογραφία', 'id' => 32],
            ['name' => 'Προπονητής Αθλημάτων', 'id' => 32],
            ['name' => 'Sports Management', 'id' => 32],
            ['name' => 'Παραγωγή', 'id' => 32],
            ['name' => 'Διοικητικό Στέλεχος Αθλητισμού', 'id' => 32],

            ['name' => 'Διαχειριστής Γεωργοκτηνοτροφικών Εκμεταλλεύσεων', 'id' => 33],
            ['name' => 'Farm Management', 'id' => 33],
            ['name' => 'Τεχνικός Αμπελουργίας & Οινολογίας', 'id' => 33],
            ['name' => 'Τεχνικός Γαλακτοκομίας – Τυροκόμος', 'id' => 33],
            ['name' => 'Τεχνικός Δασικής Προστασίας', 'id' => 33],
            ['name' => 'Τεχνικός Θερμοκηπίων και Καλλιεργιών υπό Κάλυψη', 'id' => 33],
            ['name' => 'Τεχνικός Μελισσοκομίας', 'id' => 33],
            ['name' => 'Τεχνικός Οικολογικής & Βιολογικής Γεωργίας', 'id' => 33],
            ['name' => 'Τεχνικός Βιολογικής - Οργανικής Γεωργίας', 'id' => 33],
            ['name' => 'Τεχνικός Συντήρησης και Επισκευής Γεωργικών Μηχανημάτων', 'id' => 33],
            ['name' => 'Διοίκηση Αγροτικής Οικονομίας', 'id' => 33],
            ['name' => 'Αγροτουρισμός', 'id' => 33],
            ['name' => 'Ανθοκομία', 'id' => 33],
            ['name' => 'Αρδεύσεις', 'id' => 33],
            ['name' => 'Δενδροκομία & Μεταποίηση Προϊόντων Ελιάς', 'id' => 33],
            ['name' => 'Τεχνικός Δενδροκομίας και Εναλλακτικών Δενδρωδών Καλλιεργιών', 'id' => 33],
            ['name' => 'Τεχνικός Ποτοποιίας - Αποσταγματοποιίας', 'id' => 33],
            ['name' => 'Στέλεχος Επιχειρήσεων Τυποποίησης, Μεταποίησης και Εμπορίας Αγροτικών Προϊόντων', 'id' => 33],
            ['name' => 'Διαχειριστής Συστημάτων Εκτροφής Αγροτικών Ζώων', 'id' => 33],

            ['name' => 'Κομμωτική Σκύλων', 'id' => 34],
            ['name' => 'Βοηθός Κτηνιατρικής Κλινικής', 'id' => 34],

            ['name' => 'BA (Hons) Business Management (Διοίκηση Επιχειρήσεων)', 'id' => 1], /**  κολλεγια Bachelor 1-10 */
            ['name' => 'BA (Hons) Marketing (Μάρκετινγκ)', 'id' => 1],
            ['name' => 'BSc (Hons) Economics for Business (Οικονομικά)', 'id' => 1],
            ['name' => 'BSc (Hons) Economics (Οικονομικά)', 'id' => 1],
            ['name' => 'BSc in Business Administration, Concentration in Finance', 'id' => 1],
            ['name' => 'BSc in Business Administration, Concentration in International Business', 'id' => 1],
            ['name' => 'BSc in Business Administration, Concentration in Entrepreneurial Management', 'id' => 1],
            ['name' => 'BSc in Business Administration, Concentration in Marketing', 'id' => 1],
            ['name' => 'BSc in Business Administration, Concentration in Hospitality and Tourism', 'id' => 1],
            ['name' => 'BA (Hons) Business Studies', 'id' => 1],
            ['name' => 'BA in International Management', 'id' => 1],
            ['name' => 'BA in Management', 'id' => 1],
            ['name' => 'BSc Concentration in Business Communications', 'id' => 1],
            ['name' => 'BSc Concentration in Finance', 'id' => 1],
            ['name' => 'BSc Concentration in International Business', 'id' => 1],
            ['name' => 'BSc Concentration in Marketing', 'id' => 1],
            ['name' => 'BSc in Accounting', 'id' => 1],
            ['name' => 'BSc in Applied Management', 'id' => 1],
            ['name' => 'BSc in Business Administration', 'id' => 1],
            ['name' => 'BA (Hons) - Business Studies (Finance and Accounting)', 'id' => 1],
            ['name' => 'BA (Hons) - Business Studies (Management)', 'id' => 1],
            ['name' => 'BA (Hons) - Business Studies (Marketing)', 'id' => 1],
            ['name' => 'BA (Hons) - Business Studies (Hotel and Hospitality)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (Entrepreneurship Management)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (Accounting with Finance)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (International Business)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (Marketing Communications)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (Marketing Management)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (Human Resource Management)', 'id' => 1],
            ['name' => 'BSc (Hons) in Business Administration (Operations Management)', 'id' => 1],
            ['name' => 'BSc (Hons) in Finance', 'id' => 1],
            ['name' => 'BSc (Hons) in Healthcare Management', 'id' => 1],
            ['name' => 'BSc (Hons) in International Tourism and Hospitality Management', 'id' => 1],
            ['name' => 'BSc (Hons) in Logistics and Supply Chain Management', 'id' => 1],
            ['name' => 'BSc (Hons) in Management Information Systems', 'id' => 1],
            ['name' => 'BA (Hons) in Business with Shipping', 'id' => 1],
            ['name' => 'BA Διοίκηση Επιχειρήσεων', 'id' => 1],
            ['name' => 'BA Διοίκηση Ξενοδοχειακών Μονάδων και Επιχειρήσεων Φιλοξενίας', 'id' => 1],

            ['name' => 'BSc (Hons) Maritime Business (Ναυτιλιακές Σπουδές)', 'id' => 2],
            ['name' => 'BSc (Hons) Shipping and Port Management(Διοίκηση Λιμένων και Ναυτιλιακών Επιχειρήσεων)', 'id' => 2],
            ['name' => 'BA in Marine Electrical Engineering', 'id' => 2],
            ['name' => 'BA in Navigation', 'id' => 2],

            ['name' => 'BA (Hons) International Hospitality and Tourism Management(Τουρισμός και Ξενοδοχειακές Επιχειρήσεις', 'id' => 3],
            ['name' => 'BA Culinary Arts and Food Service Development (Επισιτιστικές Τέχνες και Ανάπτυξη Υπηρεσιών Εστίασης', 'id' => 3],
            ['name' => 'BA Culinary Arts, Baking and Patisserie  (Αρτοποιία / Ζαχαροπλαστική', 'id' => 3],
            ['name' => 'BA (Hons) in Business Studies with Tourism', 'id' => 3],
            ['name' => 'BSc (Hons) International Hospitality Management', 'id' => 3],

            ['name' => 'BSc (Hons) Computing (Πληροφορική)', 'id' => 4],
            ['name' => 'BSc (Hons) Computer Networks (Πληροφορική και Δίκτυα Η/Υ)', 'id' => 4],
            ['name' => 'BEng (Hons) Electrical & Electronic Systems (Ηλεκτρολόγων – Ηλεκτρονικών Μηχανικών)', 'id' => 4],
            ['name' => 'BSc of Science in Computer Science', 'id' => 4],
            ['name' => 'BSc of Science in Business and Computing', 'id' => 4],
            ['name' => 'BSc Πληροφορική', 'id' => 4],

            ['name' => 'BSc (Hons) Nursing (Νοσηλευτική)', 'id' => 5],
            ['name' => 'BSc (Hons) Logopeadics (Λογοθεραπεία)', 'id' => 5],
            ['name' => 'BSc (Hons) Physiotherapy (Φυσικοθεραπεία)', 'id' => 5],
            ['name' => 'BSc (Hons) Biomedical Sciences (Βιοϊατρικές Επιστήμες)', 'id' => 5],
            ['name' => 'BSc (Hons) Sports Coaching (Προπονητική)', 'id' => 5],
            ['name' => 'BSc (Hons) Dietetics (Διαιτολογία)', 'id' => 5],
            ['name' => 'BSc (Hons) Occupational Therapy (Εργοθεραπεία)', 'id' => 5],
            ['name' => 'BSc (Hons) in Human Nutrition', 'id' => 5],
            ['name' => 'BSc (Hons) in Psychology', 'id' => 5],
            ['name' => 'BSc (Hons) Extended in Science', 'id' => 5],

            ['name' => 'BSc (Hons) Psychology (Ψυχολογία)', 'id' => 6],
            ['name' => 'BA (Hons) Early Childhood Studies (Προσχολική Ηλικία)', 'id' => 6],
            ['name' => 'BA (Hons) Special Education (Ειδική Αγωγή)', 'id' => 6],
            ['name' => 'BA of Laws (LLB) (Νομική)', 'id' => 6],
            ['name' => 'BSc (Hons) Politics and International Relations (Πολιτικές Επιστήμες και Διεθνείς Σχέσεις)', 'id' => 6],
            ['name' => 'BA (Hons) in English Language and English Language Teaching', 'id' => 6],
            ['name' => 'BA (Hons) in Film Studies', 'id' => 6],
            ['name' => 'BA Concentration Communication: Mass Media Production', 'id' => 6],
            ['name' => 'BA Concentration in International Relations', 'id' => 6],
            ['name' => 'BSc Concentration in Psychology', 'id' => 6],
            ['name' => 'BA (Hons) International Studies', 'id' => 6],
            ['name' => 'BSc of Arts in International Relations', 'id' => 6],
            ['name' => 'BSc of Arts in English', 'id' => 6],
            ['name' => 'BSc Ψυχολογία', 'id' => 6],
            ['name' => 'BA Αγγλική Γλώσσα και Γλωσσολογία', 'id' => 6],

            ['name' => 'BA (Hons) Architecture (Αρχιτεκτονική)', 'id' => 7],
            ['name' => 'BEng (Hons) Civil Engineering & Construction (Πολιτικών Μηχανικών)', 'id' => 7],
            ['name' => 'BEng (Hons) Electrical and Electronic Systems (Ηλεκτρολόγων - Ηλεκτρονικών Μηχανικών)', 'id' => 7],
            ['name' => 'BEng (Hons) / MEng Mechanical Engineering and Manufacturing  (Μηχανολόγων Μηχανικών)', 'id' => 7],

            ['name' => 'BA in Media Production - Journalism (Δημοσιογραφία)', 'id' => 8],
            ['name' => 'BA in Media Production - Film Directing (Σκηνοθεσία Κινηματογράφου)', 'id' => 8],
            ['name' => 'BSc (Hons) Music Technology (Μουσική Τεχνολογία)', 'id' => 8],

            ['name' => 'BA (Hons) in Communication', 'id' => 9],
            ['name' => 'BA (Hons) in Economics', 'id' => 9],
            ['name' => 'BA (Hons) in English (English and American Literature)', 'id' => 9],
            ['name' => 'BA (Hons) in English (English Literature with Linguistics)', 'id' => 9],
            ['name' => 'BSc (Hons) in Environmental Studies', 'id' => 9],
            ['name' => 'BA (Hons) in History', 'id' => 9],
            ['name' => 'BA (Hons) in Philosophy', 'id' => 9],
            ['name' => 'BA (Hons) in Sociology', 'id' => 9],
            ['name' => 'BSc (Hons) in Information Technology (Software Development)', 'id' => 9],
            ['name' => 'BSc (Hons) in Information Technology (Digital Media Technologies)', 'id' => 9],
            ['name' => 'BSc (Hons) in Information Technology (Network Technologies)', 'id' => 9],

            ['name' => 'BA (Hons) in Art History', 'id' => 10],
            ['name' => 'BA (Hons) in Contemporary Dance Practice', 'id' => 10],
            ['name' => 'BA (Hons) in Graphic Design', 'id' => 10],
            ['name' => 'BA (Hons) in Music and Music Performance', 'id' => 10],
            ['name' => 'BA (Hons) in Theater Arts', 'id' => 10],
            ['name' => 'BA (Hons) in Visual Arts', 'id' => 10],

            ['name' => 'MBA International Business (Μεταπτυχιακό στη Διοίκηση Επιχειρήσεων)', 'id' => 11], /**  κολλεγια Master 11-20 **/
            ['name' => 'MBA (Διοίκηση Επιχειρήσεων)', 'id' => 11],
            ['name' => 'MBA in Banking and Finance', 'id' => 11],
            ['name' => 'MBA in Finance', 'id' => 11],
            ['name' => 'MBA in Entrepreneurship', 'id' => 11],
            ['name' => 'MBA in Management', 'id' => 11],
            ['name' => 'MBA in General Management', 'id' => 11],
            ['name' => 'MBA in Marketing', 'id' => 11],
            ['name' => 'MBA in Marketing in the Digital Era', 'id' => 11],
            ['name' => 'MBA Executive', 'id' => 11],
            ['name' => 'MBA in Logistics Management', 'id' => 11],
            ['name' => 'MBA in Healthcare Management', 'id' => 11],
            ['name' => 'MBA in Human Resource Management', 'id' => 11],
            ['name' => 'MA in International Management – Accounting & Finance', 'id' => 11],
            ['name' => 'MA in International Management – Aviation Management', 'id' => 11],
            ['name' => 'MA in International Management – International Marketing', 'id' => 11],
            ['name' => 'MA in Transport and Logistics Management', 'id' => 11],
            ['name' => 'MSc Global Shipping Management', 'id' => 11],

            ['name' => 'MSc in Marine Engineering Management', 'id' => 12],

            ['name' => 'MBA in Hospitality (Μεταπτυχιακό στη Διοίκηση Ξενοδοχειακών Επιχειρήσεων)', 'id' => 13],
            ['name' => 'MS in Hospitality and Tourism Management', 'id' => 13],
            ['name' => 'Master 2 Management - Management of International Tourism', 'id' => 13],

            ['name' => 'MSc Software Engineering (Μεταπτυχιακό στη Μηχανική Λογισμικού)', 'id' => 14],
            ['name' => 'MSc Information Technology (Μεταπτυχιακό στην Τεχνολογία Πληροφοριών)', 'id' => 14],
            ['name' => 'MSc Information Security and Computer Forensics (Μεταπτυχιακό στην Ασφάλεια Πληροφοριών και την Ηλεκτρονική Εγκληματολογία)', 'id' => 14],
            ['name' => 'MSc in Internet Engineering and Web Management', 'id' => 14],

            ['name' => 'MSc Physiotherapy (Μεταπτυχιακό στη Φυσικοθεραπεία)', 'id' => 15],
            ['name' => 'MSc Advanced Dietetic Practice (Μεταπτυχιακό Πρόγραμμα στην Προηγμένη Διαιτολογική Πρακτική)', 'id' => 15],
            ['name' => 'MPhil - Psychology Specialisms', 'id' => 15],
            ['name' => 'MSc in Cognitive Behavioural Psychotherapies', 'id' => 15],
            ['name' => 'MSc in Psychology', 'id' => 15],

            ['name' => 'MA Special Educational Needs (SEN) (Μεταπτυχιακό στην Ειδική Αγωγή)', 'id' => 16],
            ['name' => 'ΜSc Clinical & Community Psychology (Μεταπτυχιακό στην Κλινική Κοινοτική Ψυχολογία)', 'id' => 16],
            ['name' => 'MSc Business Psychology (Μεταπτυχιακό στην Ψυχολογία της Εργασίας)', 'id' => 16],
            ['name' => 'MSc Psychology (Μεταπτυχιακό στην Ψυχολογία)', 'id' => 16],
            ['name' => 'MS in Counseling Psychology & Psychotherapy', 'id' => 16],
            ['name' => 'MA in Applied Educational Psychology', 'id' => 16],
            ['name' => 'MA in Strategic Communication & Public Relations', 'id' => 16],
            ['name' => 'MA in Digital Communication & Social Media', 'id' => 16],
            ['name' => 'MA in Teaching English to Speakers of Other Languages', 'id' => 16],
            ['name' => 'MA Counselling and Psychotherapy (Μεταπτυχιακό στη Συμβουλευτική και τη Ψυχοθεραπεία)', 'id' => 16],
            ['name' => 'MSc Applied Positive Psychology and Coaching (Εφαρμοσμένη Θετική Ψυχολογία και Ψυχολογία Coaching)', 'id' => 16],
            ['name' => 'MA Second Language Learning and Teaching', 'id' => 16],
            ['name' => 'MPhil - Education Specialisms', 'id' => 16],

            ['name' => 'MArch Architecture and Urbanism (Μεταπτυχιακό στην Αρχιτεκτονική και τον Αστικό Σχεδιασμό)', 'id' => 17],
            ['name' => 'MSc Civil Engineering and the Built Environment (Μεταπτυχιακό Πολιτικών Μηχανικών)', 'id' => 17],
            ['name' => 'MSc Electronic Systems Engineering (Μεταπτυχιακό Ηλεκτρονικών Μηχανικών)', 'id' => 17],
            ['name' => 'MSc Electrical Engineering and Computer Systems (Μεταπτυχιακό Ηλεκτρολόγων Μηχανικών και Η/Υ)', 'id' => 17],
            ['name' => 'MSc in Civil Engineering', 'id' => 17],

            ['name' => 'Ανθρωπιστικές Επιστήμες', 'id' => 37], /**  Φροντιστήρια Μέσης Εκπαίδευσης   */
            ['name' => 'Θετικές & Τεχνολογικές Επιστήμες', 'id' => 37],
            ['name' => 'Επιστήμες Υγείας', 'id' => 37],
            ['name' => 'Επιστήμες Οικονομίας και Πληροφορικής', 'id' => 37],
            ['name' => 'Επιστήμες Εκπαίδευσης', 'id' => 37],

            ['name' => 'Θετικές & Τεχνολογικές Επιστήμες', 'id' => 36],
            ['name' => 'Ανθρωπιστικές Επιστήμες', 'id' => 36],

            ['name' => 'Αγγλικά', 'id' => 38], /**  Φροντιστήρια Ξένων Γλωσσών Πληροφορικής  */
            ['name' => 'Γαλλικά', 'id' => 38],
            ['name' => 'Γερμανικά', 'id' => 38],
            ['name' => 'Ιταλικά', 'id' => 38],
            ['name' => 'Ισπανικά', 'id' => 38],
            ['name' => 'Ρωσικά', 'id' => 38],
            ['name' => 'Κινέζικα', 'id' => 38],
            ['name' => 'Βουλγάρικα', 'id' => 38],
            ['name' => 'Τουρκικά', 'id' => 38],
            ['name' => 'Πληροφορική', 'id' => 41],
            ['name' => 'Ρομποτική', 'id' => 41],

            ['name' => 'Αγγλικά', 'id' => 39],
            ['name' => 'Γαλλικά', 'id' => 39],
            ['name' => 'Γερμανικά', 'id' => 39],
            ['name' => 'Ιταλικά', 'id' => 39],
            ['name' => 'Ισπανικά', 'id' => 39],
            ['name' => 'Ρωσικά', 'id' => 39],
            ['name' => 'Κινέζικα', 'id' => 39],
            ['name' => 'Βουλγάρικα', 'id' => 39],
            ['name' => 'Τουρκικά', 'id' => 39],
            ['name' => 'Πληροφορική', 'id' => 42],
            ['name' => 'Ρομποτική', 'id' => 42],

            ['name' => 'Αγγλικά', 'id' => 40],
            ['name' => 'Γαλλικά', 'id' => 40],
            ['name' => 'Γερμανικά', 'id' => 40],
            ['name' => 'Ιταλικά', 'id' => 40],
            ['name' => 'Ισπανικά', 'id' => 40],
            ['name' => 'Ρωσικά', 'id' => 40],
            ['name' => 'Κινέζικα', 'id' => 40],
            ['name' => 'Βουλγάρικα', 'id' => 40],
            ['name' => 'Τουρκικά', 'id' => 40],
            ['name' => 'Πληροφορική', 'id' => 43],
            ['name' => 'Ρομποτική', 'id' => 43],

            ['name' => 'Latin', 'id' => 44], /**  Σχολές Χορού */
            ['name' => 'Tango', 'id' => 44],
            ['name' => 'Oriental', 'id' => 44],
            ['name' => 'Ελληνικοί Χοροί', 'id' => 44],
            ['name' => 'Κλασσικός Χορός', 'id' => 44],
            ['name' => 'Σύγχρονος Χορός', 'id' => 44],
            ['name' => 'Zumba-Fitness', 'id' => 44],
            ['name' => 'Ballroom', 'id' => 44],
            ['name' => 'Hip Hop', 'id' => 44],
            ['name' => 'Salsa', 'id' => 44],

            ['name' => 'Latin', 'id' => 45],
            ['name' => 'Tango', 'id' => 45],
            ['name' => 'Oriental', 'id' => 45],
            ['name' => 'Ελληνικοί Χοροί', 'id' => 45],
            ['name' => 'Κλασσικός Χορός', 'id' => 45],
            ['name' => 'Σύγχρονος Χορός', 'id' => 45],
            ['name' => 'Zumba-Fitness', 'id' => 45],
            ['name' => 'Ballroom', 'id' => 45],
            ['name' => 'Hip Hop', 'id' => 45],
            ['name' => 'Salsa', 'id' => 45],

            ['name' => 'Latin', 'id' => 46],
            ['name' => 'Tango', 'id' => 46],
            ['name' => 'Oriental', 'id' => 46],
            ['name' => 'Ελληνικοί Χοροί', 'id' => 46],
            ['name' => 'Κλασσικός Χορός', 'id' => 46],
            ['name' => 'Σύγχρονος Χορός', 'id' => 46],
            ['name' => 'Zumba-Fitness', 'id' => 46],
            ['name' => 'Ballroom', 'id' => 46],
            ['name' => 'Hip Hop', 'id' => 46],
            ['name' => 'Salsa', 'id' => 46],

            ['name' => 'Α Λυκείου', 'id' => 62],
            ['name' => 'Β Λυκείου', 'id' => 63],
            ['name' => 'Γ Λυκείου', 'id' => 64],

            ['name' => 'Γενική Παιδεία', 'id' => 35],
            ['name' => 'Α Γυμνασίου', 'id' => 65],
            ['name' => 'Β Γυμνασίου', 'id' => 66],
            ['name' => 'Γ Γυμνασίου', 'id' => 67],

            ['name' => 'Α Γυμνασίου', 'id' => 68],
            ['name' => 'Β Γυμνασίου', 'id' => 69],
            ['name' => 'Γ Γυμνασίου', 'id' => 70],

            ['name' => 'Α Δημοτικού', 'id' => 71],
            ['name' => 'Β Δημοτικού', 'id' => 72],
            ['name' => 'Γ Δημοτικού', 'id' => 73],
            ['name' => 'Δ Δημοτικού', 'id' => 74],
            ['name' => 'Ε Δημοτικού', 'id' => 75],
            ['name' => 'ΣΤ Δημοτικού', 'id' => 76],

            ['name' => 'BA in Graphic Design', 'id' => 10],
            ['name' => 'BA in Interior Design', 'id' => 10],
            ['name' => 'BA in Digital Design', 'id' => 10],
            ['name' => 'MA in Visual Communication', 'id' => 19],
            ['name' => 'MA in Architectural Design Communication', 'id' => 17],

//            ['name' => 'Κλασσική Μουσική', 'id' => 71],
            //            ['name' => 'Σύγχρονη-Μοντέρνα Μουσική', 'id' => 71],
            //            ['name' => 'Παραδοσιακή-Βυζαντινή Μουσική', 'id' => 71],
            //            ['name' => 'Musical', 'id' => 71],
            //            ['name' => 'Φωνητική', 'id' => 71],

        ];

        foreach ($types as $type) {
            $study = new Study;
            $study->name = $type['name'];
            // $study->id = $type['id'];
            $study->save();

            $cvteacherstudy = Cvteacherstudy::where('name', $study->name)->first();

            if (!$cvteacherstudy) {
                $cvteacherstudy = new Cvteacherstudy;
                $cvteacherstudy->name = $study->name;
                $cvteacherstudy->save();
            }
//
            //            $section = Section::find($type['section_id']);
            $section = Section::find($type['id']);
            $study->section()->toggle($section);
        }
    }
}
